# Generated by Django 3.2.7 on 2021-09-15 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='gaccha_chances',
            new_name='gacha_chances',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
