# Generated by Django 3.2.7 on 2021-09-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('GEN', 'Genernal coupons that can be used for every product')], max_length=300)),
                ('value', models.CharField(choices=[('10%', '10% discount'), ('100y', '100y discount'), ('200y', '200y discount'), ('500y', '500y discount'), ('1000y', '1000y discount'), ('10000y', '10000y discount')], max_length=150)),
                ('expire_date', models.DateField()),
                ('status', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
